#pragma once
#include <Core/STL.hpp>

namespace UVK
{
    class ScriptableObject;

    /**
     * @brief The actor manager is a simple data structure holding a set of actors allowing for native
     * scripting. The only member function called `init` is called when the engine starts up
     * @details To be more specific, inside the init function the macro ACTOR_SET_DEPLOY gets called. This macro is
     * autogenerated by the UVKBuildTool every time you create a ScriptableObject. The macro is defined under "Generated/ActorList.hpp"
     * and its job is to allocate memory for the ScriptableObject, then push it to the array of ScriptableObject*
     */
    class UVK_PUBLIC_API ActorManager
    {
    public:
        ActorManager() = default;
        ~ActorManager() noexcept;
    private:
        friend class UVKGlobal;
        friend class GameInstance;
        friend class Actor;
        friend class Events;

        std::vector<ScriptableObject*>& data() noexcept;

        void init() noexcept;
        void destroy() noexcept;
        std::vector<ScriptableObject*> a;
    };
}